/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.food.gui;

import static com.food.gui.AddSupplier.categorymap;
import com.food.model.MySQL;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABC
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }


    private void loadProduct() {

        try {

            ResultSet productRs = MySQL.search("SELECT * FROM `product`  "
                    + "INNER JOIN `category` ON `product`.`category_id`=`category`.`id` ");

//WHERE `product_name`='' AND `mesurse_type_id`=''\n" +
//"AND category_id='';
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);

            while (productRs.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(productRs.getString("id"));
                vector.add(productRs.getString("product_name"));
                vector.add(productRs.getString("category_name"));

                dtm.addRow(vector);

            }
            jTable2.setModel(dtm);
//            [255,54,11]
//            [251,82,62]
//            [0,122,255]  green 34, 139, 34

//            jTable1.getColumnModel().getColumn(0).setCellRenderer(CENTER_ALIGNMENT);
        } catch (Exception e) {
            e.printStackTrace();

        }
    }
private void reset() {
       
        jTextField7.setText("");
      
        jTable2.clearSelection();
      
        jComboBox1.setSelectedIndex(0);
     
        jTextField7.setText("Product  :");
        jTextField7.setBorder(BorderFactory.createEmptyBorder());

//        jPasswordField1.setText("");
//        jComboBox1.setSelectedIndex(0);
//        buttonGroup1.clearSelection();
//        jTextField1.grabFocus();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Food and  Vegetables", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dubai Medium", 1, 18), new java.awt.Color(0, 122, 255))); // NOI18N
        jPanel2.setRequestFocusEnabled(false);

        jTable2.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setSelectionBackground(new java.awt.Color(0, 122, 255));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton4.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/food/icon/plus.png"))); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/food/icon/updated.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/food/icon/clear.png"))); // NOI18N
        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Dubai Medium", 0, 12)); // NOI18N
        jTextField7.setText("Product  :");
        jTextField7.setSelectedTextColor(new java.awt.Color(251, 255, 255));
        jTextField7.setSelectionColor(new java.awt.Color(0, 122, 255));
        jTextField7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField7FocusLost(evt);
            }
        });
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField7)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int sr = jTable2.getSelectedRow();
        //        DecimalFormat priceFormat = new DecimalFormat("0.00");
        if (evt.getClickCount() == 1) {
            if (sr == -1) {
                JOptionPane.showMessageDialog(this, "Please Select The Row.", "Warning", JOptionPane.QUESTION_MESSAGE);

            } else {
                jTextField7.setText(jTable2.getValueAt(sr, 1).toString());
                jComboBox1.setSelectedItem(jTable2.getValueAt(sr, 2).toString());

            }
        }

        if (evt.getClickCount() == 2) {
            if (sr == -1) {
                JOptionPane.showMessageDialog(this, "Please Select The Row.", "Warning", JOptionPane.QUESTION_MESSAGE);

            } else {
                reset();
                AddMeasureType mesure = new AddMeasureType();
                mesure.setVisible(true);

                mesure.productId = Integer.valueOf(jTable2.getValueAt(sr, 0).toString());
                mesure.setMesureType(jTable2.getValueAt(sr, 1).toString());
                //                mesure.jLabel1.setText(jTable2.getValueAt(sr, 1).toString());
                mesure.loadProduct("");

            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String product = jTextField7.getText();
        String category = String.valueOf(jComboBox1.getSelectedItem());

        if (product.isBlank() || product.equals("Product  :")) {

            JOptionPane.showMessageDialog(this, "Food or  Vegetablese  required...", "Warning", JOptionPane.QUESTION_MESSAGE);
            jTextField7.setBorder(new LineBorder(Color.red, 1));
        } else if (category.equals("Please Select Category")) {

            JOptionPane.showMessageDialog(this, "Category required...", "Warning", JOptionPane.QUESTION_MESSAGE);
            jTextField7.setBorder(BorderFactory.createEmptyBorder());

        } else {

            try {

                int categoryId = categorymap.get(category);
                //                int mesurseId = mesursemap.get(mesure);

                ResultSet rs = MySQL.search("SELECT * FROM `product` "
                        + "INNER JOIN `category` ON `product`.`category_id`=`category`.`id` "
                        + " WHERE `product_name`='" + product + "'  "
                        + "AND category_id='" + categoryId + "';");

                boolean canUpdate = false;

                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Product is Already Exist...", "Warning", JOptionPane.QUESTION_MESSAGE);

                } else {
                    canUpdate = true;
                }

                if (canUpdate) {
                    MySQL.iud("INSERT INTO "
                            + "`product` (`product_name`,`category_id`)"
                            + "VALUES('" + product + "','" + categoryId + "')");

                    JOptionPane.showMessageDialog(this, "Food or  Vegetablese Registration Successfull!", "Sucsess", JOptionPane.INFORMATION_MESSAGE);

                    reset();
                    loadProduct();
            
                }

            } catch (Exception e) {

                e.printStackTrace();

            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int selectedRow = jTable2.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Plese select a row", "Warning", JOptionPane.QUESTION_MESSAGE);
        } else {

            String id = String.valueOf(jTable2.getValueAt(selectedRow, 0));

            String product = jTextField7.getText();

            String category = String.valueOf(jComboBox1.getSelectedItem());
            //            String mesure = String.valueOf(jComboBox2.getSelectedItem());

            if (product.isBlank() || product.equals("Product  :")) {

                JOptionPane.showMessageDialog(this, "Food or  Vegetablese  required...", "Warning", JOptionPane.QUESTION_MESSAGE);
                jTextField7.setBorder(new LineBorder(Color.red, 1));
            } else if (category.equals("Please Select Category")) {

                JOptionPane.showMessageDialog(this, "Category required...", "Warning", JOptionPane.QUESTION_MESSAGE);
                jTextField7.setBorder(BorderFactory.createEmptyBorder());

            } else {

                int categoryId = categorymap.get(category);

                boolean canUpdate = false;
                try {

                    ResultSet rs = MySQL.search("SELECT * FROM `product` "
                            + "INNER JOIN `category` ON `product`.`category_id`=`category`.`id` "
                            + " WHERE `product_name`='" + product + "'  "
                            + "AND category_id='" + categoryId + "';");

                    if (rs.next()) {
                        JOptionPane.showMessageDialog(this, "Product is Already Exist...", "Warning", JOptionPane.QUESTION_MESSAGE);

                    } else {
                        canUpdate = true;
                    }
                    if (canUpdate) {

                        MySQL.iud("UPDATE `product` SET "
                                + "`product_name` = '" + product + "',"
                                + "`category_id` = '" + categorymap.get(category) + "'"
                                + "WHERE `id` = '" + id + "'");
                        JOptionPane.showMessageDialog(this, "Food or Vegetablese Update Successfull!", "Food or  Vegetablese", JOptionPane.INFORMATION_MESSAGE);
                        reset();
                        loadProduct();
                    
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        reset();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField7FocusLost
        if (jTextField7.getText().length() == 0) {
            jTextField7.setText("Product  :");
        }
    }//GEN-LAST:event_jTextField7FocusLost

    private void jTextField7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MousePressed
        if (jTextField7.getText().equals("Product  :")) {
            jTextField7.setText("");
        }
    }//GEN-LAST:event_jTextField7MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
